# Generated by Django 4.2.4 on 2023-08-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_user_email_address_alter_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_Address',
            new_name='email',
        ),
    ]
