# Generated by Django 4.2.4 on 2023-08-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_email_address_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (), 'verbose_name': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Videos'},
        ),
        migrations.AlterField(
            model_name='author',
            name='author_ID',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='img.png', upload_to='upload/images'),
        ),
    ]
