# Generated by Django 4.2.4 on 2023-08-05 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_author_options_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_ID',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
