# Generated by Django 4.2.4 on 2023-08-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_author_author_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Authors'},
        ),
    ]
