# Generated by Django 4.2.4 on 2023-08-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('create_new_author', 'create_new_author'), ('edit_author', 'edit_author'), ('get_all_authors', 'get_all_authors'), ('delete_author_details', 'delete_author_details'), ('delete_authors', 'delete_authors'), ('create_new_video', 'create_new_video'), ('delete_video', 'delete_video'), ('edit_video', 'edit_video'), ('get_videos', 'get_videos'), ('create_new_comment', 'create_new_comment'), ('edit_comment', 'edit_comment'), ('delete_comment', 'delete_comment'), ('get_all_videos', 'get_all_videos'), ('get_comment', 'get_comment')], 'verbose_name': 'Authors'},
        ),
    ]
